apiVersion: apps/v1
kind: Deployment
metadata:
  name: hcl
  labels:
    org: kyndryl
spec:
  template:
    metadata:
      labels: 
        app: hcl
    spec:
      containers:
      - name: app
        image: mahijs/kyndryl_ibm:latest
        ports:
        - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      app: hcc
